In [20]:
import pandas as pd

# Load the correct sheet with actual loan data
file_path = r"C:\Users\Hp\Downloads\Compressed\loan_data.xlsx"
df = pd.read_excel(file_path, sheet_name='Data')

# === Preview the data ===
print("ðŸ”¹ First 5 Rows:")
print(df.head())

print(f"\nðŸ”¹ Dataset Shape: {df.shape}")

print("\nðŸ”¹ Column Info:")
print(df.info())

print("\nðŸ”¹ Missing Values:")
print(df.isnull().sum())

print("\nðŸ”¹ Summary Statistics:")
print(df.describe(include='all'))

print("\nðŸ”¹ Column Names:")
print(df.columns.tolist())

ðŸ”¹ First 5 Rows:
   ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0
1   2   45          19      34     90089       3    1.5          1         0
2   3   39          15      11     94720       1    1.0          1         0
3   4   35           9     100     94112       1    2.7          2         0
4   5   35           8      45     91330       4    1.0          2         0

   Personal Loan  Securities Account  CD Account  Online  CreditCard
0              0                   1           0       0           0
1              0                   1           0       0           0
2              0                   0           0       0           0
3              0                   0           0       0           0
4              0                   0           0       0           1

ðŸ”¹ Dataset Shape: (5000, 14)

ðŸ”¹ Column Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB
None

ðŸ”¹ Missing Values:
ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

ðŸ”¹ Summary Statistics:
                ID          Age   Experience       Income      ZIP Code  \
count  5000.000000  5000.000000  5000.000000  5000.000000   5000.000000
mean   2500.500000    45.338400    20.104600    73.774200  93152.503000
std    1443.520003    11.463166    11.467954    46.033729   2121.852197
min       1.000000    23.000000    -3.000000     8.000000   9307.000000
25%    1250.750000    35.000000    10.000000    39.000000  91911.000000
50%    2500.500000    45.000000    20.000000    64.000000  93437.000000
75%    3750.250000    55.000000    30.000000    98.000000  94608.000000
max    5000.000000    67.000000    43.000000   224.000000  96651.000000

            Family        CCAvg    Education     Mortgage  Personal Loan  \
count  5000.000000  5000.000000  5000.000000  5000.000000    5000.000000
mean      2.396400     1.937913     1.881000    56.498800       0.096000
std       1.147663     1.747666     0.839869   101.713802       0.294621
min       1.000000     0.000000     1.000000     0.000000       0.000000
25%       1.000000     0.700000     1.000000     0.000000       0.000000
50%       2.000000     1.500000     2.000000     0.000000       0.000000
75%       3.000000     2.500000     3.000000   101.000000       0.000000
max       4.000000    10.000000     3.000000   635.000000       1.000000

       Securities Account  CD Account       Online   CreditCard
count         5000.000000  5000.00000  5000.000000  5000.000000
mean             0.104400     0.06040     0.596800     0.294000
std              0.305809     0.23825     0.490589     0.455637
min              0.000000     0.00000     0.000000     0.000000
25%              0.000000     0.00000     0.000000     0.000000
50%              0.000000     0.00000     1.000000     0.000000
75%              0.000000     0.00000     1.000000     1.000000
max              1.000000     1.00000     1.000000     1.000000

ðŸ”¹ Column Names:
['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg', 'Education', 'Mortgage', 'Personal Loan', 'Securities Account', 'CD Account', 'Online', 'CreditCard']